for(lam=0.6e-6;lam<=0.7e-6;lam=lam+0.001e-6){
    switchtolayout;
    select("source");
    shiftselect("source_1");
    set("wavelength start", lam);
    set("wavelength stop", lam);
    run;
    
    T = real(-(transmission("monitor")));
    
    outdata = [ lam*1e9, pinch(T)];
    format long;
    filename = "Data/Au_t-ES_1.txt";
    write(filename,num2str(outdata));
    print("Wavelength " + num2str(lam*1e9) + " nm complete");
}
print("done");